Repository pagarme/pagarme-js, pull requests merged in 2019-05, with the labels that each got.

#164 mastercard: update bins (3.9.2)
  .travis.yml
  browser/pagarme.js
  browser/pagarme.js.map
  browser/pagarme.min.js
  lib/validations/validate/card/bins.js
  package-lock.json
  package.json
  pagarme.js
  pagarme.js.map
  pagarme.min.js
Labels: cos:expedite, enhancement

#163 mastercard: update bins (4.1.1)
  .travis.yml
  lib/validations/validate/card/bins.js
Labels: cos:expedite, enhancement

#166 transfers: add params in limits request
  lib/resources/transfers.js
  lib/resources/transfers.spec.js
Labels: cos:standard, review-needed

#168 release: bump version to 4.1.1
  browser/pagarme.js
  browser/pagarme.js.map
  browser/pagarme.min.js
  package.json
  pagarme.js
  pagarme.js.map
  pagarme.min.js
Labels: bug, cos:standard, review-needed

#173 Add payables days route
  lib/resources/payables.js
  lib/resources/payables.spec.js
  lib/routes.js
Labels: cos:expedite, enhancement, review-needed

#177 Bump version
  README.md
  browser/pagarme.js
  browser/pagarme.js.map
  browser/pagarme.min.js
  package.json
  pagarme.js
  pagarme.js.map
  pagarme.min.js
Labels: cos:standard, pagarme-js docs, review-needed

#178 Refactor UserAgent usage
  lib/request.js
Labels: bug, cos:expedite

#180 Update version
  browser/pagarme.js
  browser/pagarme.js.map
  browser/pagarme.min.js
  package.json
  pagarme.js
  pagarme.js.map
  pagarme.min.js
Labels: bug, cos:expedite, review-needed
