Repository pagarme/pagarme-js, pull requests merged in 2019-06, with the labels that each got.

#183 Refactor version origin
  .eslintrc
  lib/request.js
  webpack.config.js
Labels: bug, cos:standard, review-needed

#185 Update version
  browser/pagarme.js
  browser/pagarme.js.map
  browser/pagarme.min.js
  package.json
  pagarme.js
  pagarme.js.map
  pagarme.min.js
Labels: cos:standard, enhancement, review-needed

#186 Update CDN link
  README.md
Labels: enhancement, pagarme-js docs, review-needed

#188 api: add versions resource to client
  lib/resources/index.js
  lib/resources/versions.js
  lib/resources/versions.spec.js
  lib/routes.js
Labels: enhancement

#190 Release 4.4.0
  browser/pagarme.js
  browser/pagarme.js.map
  browser/pagarme.min.js
  package-lock.json
  package.json
  pagarme.js
  pagarme.js.map
  pagarme.min.js
Labels: cos:standard, enhancement

#191 chore: update readme cdn link to 4.4
  README.md
Labels: cos:standard
