Repository pagarme/pagarme-js, pull requests merged in 2019-10, with the labels that each got.

#205 Release 4.5.0
  README.md
  browser/pagarme.js
  browser/pagarme.js.map
  browser/pagarme.min.js
  package.json
  pagarme.js
  pagarme.js.map
  pagarme.min.js
Labels: cos:standard

#206 Authentication - Add options to login
  lib/client/strategies/login.js
Labels: enhancement, review-needed

#209 chore: bump version to 4.5.1
  browser/pagarme.js
  browser/pagarme.js.map
  browser/pagarme.min.js
  package.json
  pagarme.js
  pagarme.js.map
  pagarme.min.js
Labels: bug, cos:standard
